CREATE SCHEMA `DDDLesson`;

DROP TABLE `stock`;
DROP TABLE `stock_daily_record`;
DROP TABLE `book`;
DROP TABLE `book_category`;

DROP TABLE IF EXISTS `stock`;
CREATE TABLE `stock` (
  `ID` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `STOCK_CODE` varchar(10) NOT NULL,
  `STOCK_NAME` varchar(20) NOT NULL,
   PRIMARY KEY (`ID`) USING BTREE,
   UNIQUE KEY `UNI_STOCK_NAME` (`STOCK_NAME`),
   UNIQUE KEY `UNI_STOCK_ID` (`STOCK_CODE`) USING BTREE
)  ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8;

DROP TABLE IF EXISTS `dddlesson`.`stock_daily_record`;
CREATE TABLE  `dddlesson`.`stock_daily_record` (
  `ID` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `PRICE_OPEN` float(6,2) DEFAULT NULL,
  `PRICE_CLOSE` float(6,2) DEFAULT NULL,
  `PRICE_CHANGE` float(6,2) DEFAULT NULL,
  `VOLUME` bigint(20) unsigned DEFAULT NULL,
  `DATE` date NOT NULL,
  `STOCK_ID` int(10) unsigned NOT NULL,
   PRIMARY KEY (`ID`) USING BTREE,
   UNIQUE KEY `UNI_STOCK_DAILY_DATE` (`DATE`),
   KEY `FK_STOCK_TRANSACTION_STOCK_ID` (`STOCK_ID`),
   CONSTRAINT `FK_STOCK_TRANSACTION_STOCK_ID` FOREIGN KEY (`STOCK_ID`) REFERENCES `stock` (`ID`)
)  ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8;

DROP TABLE IF EXISTS `book_category`;
CREATE TABLE  `book_category` (
  `ID` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `NAME_CATEGORY` varchar(20) NOT NULL,
  `CODE_CATEGORY` varchar(20) NOT NULL,
   PRIMARY KEY (`ID`) USING BTREE
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8;

DROP TABLE IF EXISTS `book`;
CREATE TABLE `book` (
  `ID` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `NAME` varchar(10) NOT NULL,
  `TIME_CREATE` date NOT NULL,
   PRIMARY KEY (`ID`) USING BTREE,
   UNIQUE KEY `UNI_NAME` (`NAME`),
  `BOOK_ID` int(10) unsigned NOT NULL,
   KEY `FK_BOOK_TRANSACTION_BOOK_ID` (`BOOK_ID`),
   CONSTRAINT `FK_BOOK_TRANSACTION_BOOK_ID` FOREIGN KEY (`BOOK_ID`) REFERENCES `book_category` (`ID`)
)  ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8;





